woowa-techcamp-2021/deal-8

- front/public/login.html
- front/public/main.html
퍼블리싱을 위한 준비 작업입니다. @SecretJuJu
> etc: publcing 작업준비

- frontend/public/css/normalize.css
- frontend/public/main.html
normalize.css에 width, height 등의 기본적인 스타일 적용
normalize.css 파일 추가 및 위 내용 작성
> [MarkUp] 퍼블리싱 작업을 위한 사전 작업

- frontend/public/css/normalize.css
#38
Normalize css 코드의 수정해야 할 것들을 수정하여 올립니다.
1. css 테스트 과정중 사용한 body의 border를 삭제
2. body의 padding 제거
- padding이 필요없어서 제거하여 올립니다.
3.body를 가운데로 옮김
- body를 absolute로 하여 화면의 가운데로 옮겼습니다. (보기 편하기 위해)
4. body의 display를 flex로 변경하였습니다.
> fix: Normalize 코드 수정사항

- frontend/public/css/chat.css
- frontend/public/css/location.css
- frontend/public/css/main.css
- frontend/public/css/normalize.css
- frontend/public/icon/add.svg
- frontend/public/location.html
- frontend/public/main.html
#12
내동네 설정하기 화면 레이아웃 작업을 진행했습니다.
동네 추가 제거를 위한 모달작업은 자바스크립트가 필요해서 스케쥴 상 SPA 구조로 전환하는 과정에 처리하도록 하겠습니다.
publicing된 결과물간에 링크를 a태그로 연결해놓겠습니다.
추후에 blur 처리를 구현해야합니다.
> [Markup] 내 동네 설정하기 페이지 레이아웃과 스타일 #12

- frontend/public/detailPost.html
- frontend/public/js/menu/menuEvent.js
Link 연결 과 퍼블리싱 결과 확인하면서 발견한 버그 해결
> fix: 퍼블리싱 리뷰를 하다가 발견한 버그 수정

- frontend/src/api/user.js
- frontend/src/helper/eventHelpers.js
- frontend/src/page/HomePage/Controller.js
- frontend/src/page/HomePage/index.js
- frontend/src/page/HomePage/views/MainHeaderView.js
- frontend/src/page/MenuPage/index.js
- frontend/src/public/css/common/chat_list_item.css
- frontend/src/public/css/common/drop_down.css
- frontend/src/public/css/common/product_list_item.css
- frontend/src/public/css/main.css
- frontend/src/public/css/menu.css
- frontend/src/router.js
#13 
- 메인페이지 헤더의 location에 드롭다운 구성과 createPost 버튼
- 메인페이지 헤더 location 드롭다운
- createPost 버튼에 a 태그 사이즈
- 드롭다운 마지막에 위치추가 버튼
- 헤더에서 locations 파라미터 받기
- Product 클릭시 리다이랙트
- 위 두 사항을 추가 구현해야합니다.
> [FrontEnd] 메인페이지 위치 드롭다운

- deploy.sh
> [Fix] 배포 스크립트 수정입니다.

- frontend/src/page/HomePage/views/MainHeaderView.js
- frontend/src/page/MenuPage/Controller.js
- frontend/src/page/MenuPage/Store.js
- frontend/src/page/MenuPage/views/TabView.js
- frontend/src/page/ProductDetailPage/Controller.js
- frontend/src/page/ProductDetailPage/views/ProductDetailFooterView.js
- frontend/src/public/css/menu.css
탭 메뉴 화면 기능구현입니다.
탭을 누르면 스라이딩되는 효과와 각 탭 속에서 사용되는 코드들을  수정했습니다.
기본적인 슬라이딩 방식은 퍼블리싱에서 했던 작업과 유사하지만 코드 자체는 새로 작성했습니다.
스크린샷은 데모로 확인
> [FE] 탭 메뉴 화면 기능 구현입니다.(슬라이딩)

- frontend/src/api/chat.js
- frontend/src/api/product.js
- frontend/src/common/views/ProductListView.js
- frontend/src/page/HomePage/index.js
- frontend/src/page/LoginPage/index.js
- frontend/src/page/MenuPage/index.js
- frontend/src/page/MenuPage/views/ChatRoomListView.js
- frontend/src/page/ProductDetailPage/Controller.js
- frontend/src/page/ProductDetailPage/Store.js
- frontend/src/page/ProductDetailPage/index.js
- frontend/src/page/ProfilePage/index.js
- frontend/src/page/SignupPage/index.js
#1
- es6-string-html 플러그인을 적극적으로 사용하기위해 리터럴 문자열 표현앞에 `/*html*/` 코드들을 추가했습니다.
- svg들을 img로 변경했습니다.!!
url을 통해 접속할 경우, webpack dev-server와 expressjs 배포했을 경우, static file을 찾이못하는 라우팅 문제가 있었는데
```javascript
app.get("/app", (req, res) => {
res.sendFile(path.join(__dirname, "index.html"));
});
```
아래와 같은 백엔드 API가 필요합니다.
> [Refactoring] 잡다한 리펙토링입니다. 내용 참고 해주세요.

- frontend/src/common/views/DropDownMenuView.js
- frontend/src/page/ProductDetailPage/views/ProductDetailHeaderView.js
- frontend/src/page/ProductDetailPage/views/ProductDetailView.js
- frontend/src/page/ProductDetailPage/views/ProductImageListView.js
- frontend/src/public/css/common/drop_down.css
- frontend/src/public/css/detailPost.css
상품 상세 화면에 드롭다운들을 변경했습니다.
outfocus 됐을 때 드롭다운이 다시 축소되도록 구현했습니다.
@SecretJuJu
> [Refactoring] 상품 상세 화면에 드롭다운 기능을 추가했습니다.

- frontend/src/api/user.js
- frontend/src/page/LocationPage/Controller.js
- frontend/src/page/LocationPage/Store.js
- frontend/src/page/LocationPage/index.js
- frontend/src/page/LocationPage/views/AddLocationModalView.js
- frontend/src/page/LocationPage/views/DeleteLocationModalView.js
- frontend/src/page/LocationPage/views/LocationCommentView.js
- frontend/src/page/LocationPage/views/LocationListView.js
- frontend/src/page/ProductDetailPage/views/ProductDetailHeaderView.js
- frontend/src/page/ProductDetailPage/views/ProductDetailView.js
- frontend/src/public/css/detailPost.css
- frontend/src/public/css/location.css
- frontend/src/public/css/main.css
- frontend/src/public/svg/add.svg
#21
내 동네 설정하기 화면 기능구현과 관련된 PR입니다.
동네 추가와 삭제를 위한 모달 화면을 추가했습니다.
- 메인 화면 동네 설정하기 드롭다운 메뉴 중 "내동네 설정하기" 를  클릭시 동네 설정화면으로 이동하는 기능 구현
- 내 동네 설정 화면에서 가지고 있는 동네를 제거를 위한 모달 추가
- 내 동네 설정 화면에서 동네를 추가하기 위한 모달 추가
- 내 동네 제거 모달 화면
-  내 동네 추가 모달
>  [FE] 내 동네 설정하기 화면 기능 구현 #21

- frontend/src/page/CreatePostPage/Controller.js
- frontend/src/page/CreatePostPage/index.js
- frontend/src/page/CreatePostPage/views/CreatePostFormView.js
글 쓰기 화면에서 위치 정보를 사용자 정보를 기반으로 자동 등록하기 위해서 data fetching 을 추가했습니다.
CreatePostPage 의 생성자에서 데이터 패치 작업 추가
> refactoring: data초기 패치를 통한 location설정

- backend/package-lock.json
- backend/package.json
- backend/src/model/Product/AbstractProductStore.js
- backend/src/model/Product/Product.js
- backend/src/model/Product/Store/InMemoryProductStore.js
- backend/src/routes/api/product/index.js
- backend/src/util/HttpStatus.js
- 저번에 올린 PR 버그 픽스 및 리팩토링
- update, delete 과정에 author 검사
- category 없이도 상품 조회 가능 
- http status 코드 적용
> [Backend] 백엔드 Product mock api 버그 Fix, 리팩토링

- frontend/src/page/CreatePostPage/Controller.js
- frontend/src/page/HomePage/Controller.js
- frontend/src/page/HomePage/Store.js
- frontend/src/page/HomePage/index.js
- frontend/src/page/HomePage/views/NewProductButtonView.js
로그인 여부에 따른 UX/UI 수정입니다.
- 글쓰기 화면에서 로그인이 되어있지 않으면 로그인화면으로 강제 이동하도록 수정했습니다.
- 홈화면에서 FAB(글쓰기로 이동하는 버튼)을 로그인되어있지않으면 보이지않도록했습니다.
> Fix: Home FAB Button hide when unauthentication

- backend/src/model/Account/Store/InMemmoryAccountStore.js
- backend/src/routes/api/account/index.js
- frontend/src/api/user.js
- frontend/src/common/views/DropDownMenuView.js
- frontend/src/page/CreatePostPage/Controller.js
- frontend/src/page/HomePage/Controller.js
- frontend/src/page/HomePage/Store.js
- frontend/src/page/HomePage/index.js
- frontend/src/page/HomePage/views/NewProductButtonView.js
- frontend/src/page/LocationPage/Controller.js
- frontend/src/public/css/common/drop_down.css
#31
내 동네 설정하기 화면 기능 구현을 완료했습니다.
- 회원가입 API에서 location 이 저장되지않아 수정
- `POST /api/account/me/locatoin` 를 이용한 내 동네 추가 기능
- `DELETE /api/account/me/location?location=[내동네]`를 이용한 내동네 제거 기능 추가
> [BE] 내동네 설정하기 화면 기능 구현 API #31

- backend/.gitignore
- backend/package-lock.json
- backend/package.json
- backend/src/app.js
- backend/src/routes/api/product/index.js
- backend/src/routes/index.js
- backend/src/views/file.ejs
이미지 업로드 API 추가 했습니다.
리뷰부탁드립니다.
- 이미지 업로드를 위한 Multer library 추가했습니다.
- `POST /api/product/media` API 기능을 추가했습니다.
> [BE] Image Upload API 추가

- backend/src/model/Product/Store/InMemoryProductStore.js
- backend/src/routes/api/product/index.js
- frontend/src/api/product.js
- frontend/src/page/HomePage/Controller.js
- frontend/src/page/HomePage/Store.js
- frontend/src/page/HomePage/index.js
- frontend/src/page/HomePage/views/CategoryView.js
- frontend/src/page/HomePage/views/MainHeaderView.js
- frontend/src/public/css/main.css
완성된 API 들을 이용해서 프론트엔드 기능 구현 완료.
카테고리와 로케이션 정보를 기반으로 상품정보들을 필터링할 수 있도록 구현했습니다.
추가로 현재 어떤 카테고리로 필터링하고 있는지 보여주는 라벨링을 추가했습니다.
> [BE/FE] REST API를 이용해서 메인화면 기능 구현 완료 

- backend/package-lock.json
- backend/package.json
- backend/sql/create_account.sql
- backend/sql/create_location.sql
- backend/src/app.js
- backend/src/config/mysql.js
- backend/src/model/Account/AbstractAccountStore.js
- backend/src/model/Account/Store/MySQLAccountStore.js
- backend/src/routes/api/account/index.js
- backend/src/routes/api/auth/index.js
- MysqlAccountStore에 getAccount, createAccount 기능을 추가했습니다.
- /api/auth의 accountStore를 MysqlAccountStore로 변경
- /api/account의 me를 MysqlAccountStore로 변경
- app.js에 mysql 커넥션 export
> [Backend] 백엔드 api MysqlAccountStore 

- backend/src/middlewares/auth.js
- backend/src/model/Account/Store/MySQLAccountStore.js
- backend/src/routes/api/account/index.js
- authMiddleware를 만들고 account api에 미들웨어를 추가했습니다.
- /src/middlewares/auth.js 에 authMiddleware를 만들었습니다.
- account api 에 모두 authMiddleware가 필요하여 적용하였습니다.
> [Backend] authMiddleware 추가, account api에 authMiddleware 적용

- backend/sql/create_category.sql
- backend/sql/create_interest_product.sql
- backend/sql/create_product.sql
- backend/sql/insert_category.sql
- backend/sql/insert_product.sql
- backend/src/app.js
- backend/src/clearDatabaseTables.js
- backend/src/createDatabaseTables.js
- backend/src/mock/mockMySQLData.js
- backend/src/model/Account/Store/MySQLAccountStore.js
- backend/src/model/Category/AbstractCategoryStore.js
- backend/src/model/Category/Category.js
- backend/src/model/Category/Store/MySQLCategoryStore.js
- backend/src/model/Product/AbstractProductStore.js
- backend/src/model/Product/Product.js
- backend/src/model/Product/ProductStatus.js
- backend/src/model/Product/Store/InMemoryProductStore.js
- backend/src/model/Product/Store/MySQLProductStore.js
- backend/src/populateExampleData.js
- backend/src/routes/api/account/index.js
- backend/src/routes/api/product/index.js
- frontend/src/api/product.js
- frontend/src/page/HomePage/Controller.js
- frontend/src/public/css/main.css
InMemory___Store들을 MySQL___Store로  교체중입니다.
이번 PR은 그 중 Product 관련 Store 작업 중입니다.
getProducts와 createProdcut 쿼리 작성과 Store 구현체 변경을 진행했습니다.
이번에 사용된 DDL 쿼리들은 `/backend/sql` 디렉토리에 추가해뒀습니다. 참고해주세요.
(추후 내용을 추가할 예정입니다.)
> [BE] MySQLProductStore 관련 개발 내용입니다.

- backend/src/clearDatabaseTables.js
- backend/src/createDatabaseTables.js
- backend/src/model/Product/Store/MySQLProductStore.js
- backend/src/populateExampleData.js
- backend/src/routes/api/product/index.js
- frontend/src/page/HomePage/Controller.js
Product 관련 API들은 쿼리가 많아서 PR을 나눠서 진행하겠습니다.
우선 이번 PR에서는 `GET /api/product?category=1&location=A`를 이용한 필터링 해주는 기능에 집중했습니다.
리뷰 부탁드립니다.!
코드가 좀 많이 복잡해졌는데 나중에 쿼리관련 처리는 몰아서 리팩토링해보겠습니다.
> Add: product fileter API 기능 구현

- backend/sql/insert_category.sql
- backend/src/model/Product/AbstractProductStore.js
- backend/src/model/Product/Product.js
- backend/src/model/Product/Store/MySQLProductStore.js
- backend/src/routes/api/account/index.js
- frontend/src/api/product.js
- frontend/src/api/user.js
- frontend/src/page/HomePage/Controller.js
- frontend/src/page/MenuPage/Controller.js
메인화면에서 상품 게시글 목록과 관심상품 추가 토글 버튼 기능을 완료했습니다. :)
MySQLProductStore 속 interest_product를 이용한 query를 작성했습니다.
그리고
프론트엔드 HomePage Controller의 비어있던 함수 내용을 API를 호출하는 코드와 리렌더링 코드를 추가했습니다.
메뉴 화면에서 관심상품 리스트는 아직 추가되지 않았습니다.
> [BE] 메인화면 기능 구현 완료했습니다.

- backend/process.json
- backend/src/clearDatabaseTables.js
- backend/src/createDatabaseTables.js
- backend/src/model/Product/AbstractProductStore.js
- backend/src/model/Product/Store/MySQLProductStore.js
- backend/src/populateExampleData.js
- backend/src/routes/api/account/index.js
- backend/src/routes/api/auth/index.js
- backend/src/routes/api/product/index.js
- backend/src/routes/index.js
- backend/src/views/file.ejs
- frontend/src/api/product.js
- frontend/src/common/views/ProductListView.js
- frontend/src/page/CreatePostPage/Controller.js
- frontend/src/page/ProductDetailPage/views/ProductImageListView.js
- frontend/src/public/css/detailPost.css
- frontend/webpack.config.js
이미지 업로드와 글쓰기 기능을 전반적으로 완료했습니다.
- image upload api를 먼저 호출한 후, 업로드된 이미지 경로들을 토대로 상품을 등록하는 API `POST /api/product/`를 호출하는 방식을 사용합니다.
- 상품등록이 끝나면 상품 상세 보기 화면으로 자동으로 네비게이션됍니다.
배포 서버에서 정상적으로 동작하는지 테스트해야합니다.
- 상품 삭제, 수정 기능을 추가 구현해야합니다.
> [FE/BE] 이미지 업로드와 글쓰기 기능 구현 완료

- frontend/src/common/views/ProductListView.js
- frontend/src/page/ChatRoomListPage/views/ChatRoomListContentView.js
- frontend/src/page/MenuPage/views/ChatRoomListView.js
- frontend/src/public/css/common/chat_list_item.css
- frontend/src/public/css/common/product_list_item.css
- frontend/src/public/css/menu.css
#108 
- 각 list item들의 간격을 보여주기 위한 splitter를 만들었습니다.
- 메인화면 상품리스트에 splitter 적용
- 메뉴화면의 각 아이템들에 splitter 적용
- /chatList/:productId 페이지에도 splitter 적용
> [Frontend] Splitter 구현

- backend/src/model/Product/Store/MySQLProductStore.js
배포전 홈화면에서 chat count 쿼리 문제로  쿼리 수정후  다시 올립니다.
> fix:버그로인해 홈화면에서 chat count 제거

- frontend/src/page/ProductDetailPage/views/ProductDetailModalView.js
긴급 버그 수정입니다.!!!
@SecretJuJu 
상품 상세화면의 모달의 상위 클래스를 모달 View로 변경했습니다.
> fix: modal bug

- backend/src/model/Chat/Store/MySQLChatStore.js
채팅 목록을 최신순으로 가져오지 못해서 SQL 쿼리문을 수정했습니다. @SecretJuJu
> fix: 채팅목록 최신순으로 가져오도록 수정
